/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.components;

import AppPackage.AnimationClass;
import com.components.player.layoutsample1;
import com.components.player.Fourvideo;
import com.components.textscroll.textscrollWizard;
import com.components.wizard.picturescreen;
import com.components.wizard.store;
import com.components.wizard.videoscreen;
import com.components.wizard.videotext;
import javax.swing.ImageIcon;
import com.components.wizard.layout2media;
import com.components.wizard.storepic;
import com.components.wizard.layouttest;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 *
 * @author lenovo
 */
public class Home extends javax.swing.JFrame {
    Connection connection = null;
PreparedStatement pst = null;
ResultSet rs = null;
      AnimationClass ac = new AnimationClass();
       public Home() {
            connection = mysqlconnect.ConnectDb();
        initComponents();
        glide();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        video = new javax.swing.JLabel();
        pictext = new javax.swing.JLabel();
        videotxt = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        video1 = new javax.swing.JLabel();
        pictext1 = new javax.swing.JLabel();
        videotxt1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setFont(new java.awt.Font("Wide Latin", 2, 14)); // NOI18N
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(1400, 700));
        ImageIcon icon1 = createImageIcon("ICONS/TABBED_PANE_ICONS/home.png");
        ImageIcon icon2 = createImageIcon("ICONS/TABBED_PANE_ICONS/display log.png");
        ImageIcon icon3 = createImageIcon("ICONS/TABBED_PANE_ICONS/playlist.png");
        ImageIcon icon4 = createImageIcon("ICONS/TABBED_PANE_ICONS/content setup.png");

        jTabbedPane1.addTab("Home", icon1, jPanel1);
        jTabbedPane1.addTab("Store", icon2, jPanel2);
        jTabbedPane1.addTab("Setup Playlist", icon3, jPanel3);
        jTabbedPane1.addTab("Manage Content", icon4, jPanel4);

        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        video.setBackground(new java.awt.Color(51, 0, 51));
        video.setFont(new java.awt.Font("Trajan Pro 3", 3, 24)); // NOI18N
        video.setForeground(new java.awt.Color(51, 51, 255));
        video.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/components/buttons/default.png"))); // NOI18N
        video.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        video.setOpaque(true);
        video.setPreferredSize(new java.awt.Dimension(180, 60));
        video.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                videoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                videoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                videoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                videoMousePressed(evt);
            }
        });
        jPanel1.add(video, new org.netbeans.lib.awtextra.AbsoluteConstraints(-350, 190, -1, -1));

        pictext.setBackground(new java.awt.Color(51, 0, 51));
        pictext.setFont(new java.awt.Font("Trajan Pro 3", 3, 24)); // NOI18N
        pictext.setForeground(new java.awt.Color(51, 0, 255));
        pictext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/components/buttons/Picturedefault.png")));
        pictext.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pictext.setOpaque(true);
        pictext.setPreferredSize(new java.awt.Dimension(180, 60));
        pictext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pictextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pictextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pictextMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pictextMousePressed(evt);
            }
        });
        jPanel1.add(pictext, new org.netbeans.lib.awtextra.AbsoluteConstraints(-350, 290, -1, 60));

        videotxt.setBackground(new java.awt.Color(51, 0, 51));
        videotxt.setFont(new java.awt.Font("Trajan Pro 3", 3, 24)); // NOI18N
        videotxt.setForeground(new java.awt.Color(51, 51, 255));
        videotxt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/components/buttons/Videodefault.png")));
        videotxt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        videotxt.setOpaque(true);
        videotxt.setPreferredSize(new java.awt.Dimension(180, 60));
        videotxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                videotxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                videotxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                videotxtMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                videotxtMousePressed(evt);
            }
        });
        videotxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                videotxtKeyPressed(evt);
            }
        });
        jPanel1.add(videotxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(-350, 380, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/components/buttons/Untitled-1.png")));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel5MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel5MousePressed(evt);
            }
        });
        jLabel5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel5KeyPressed(evt);
            }
        });
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 300, 150, 50));

        jLabel1.setBackground(new java.awt.Color(102, 0, 102));
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Kumar\\Desktop\\home.jpg")); // NOI18N
        jLabel1.setOpaque(true);
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 672));

        jTabbedPane1.addTab("Home", jPanel1);
        jTabbedPane1.addTab("Home", icon1, jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Kumar\\Documents\\NetBeansProjects\\DigitalSignage\\src\\com\\components\\storage.jpg")); // NOI18N
        jLabel3.setPreferredSize(new java.awt.Dimension(1395, 672));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel4KeyPressed(evt);
            }
        });
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 450, 320));

        jTabbedPane1.addTab("Store", jPanel2);
        jTabbedPane1.addTab("Store", icon2, jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Trajan Pro", 3, 11)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Kumar\\Documents\\NetBeansProjects\\DigitalSignage\\src\\com\\components\\ICONS\\playlistbutton.png")); // NOI18N
        jButton1.setText("Setup Playlist");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, -1, -1));

        jButton3.setText("Scrolling text control");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 70, 180, 50));

        video1.setBackground(new java.awt.Color(51, 0, 51));
        video1.setFont(new java.awt.Font("Trajan Pro 3", 3, 24)); // NOI18N
        video1.setForeground(new java.awt.Color(51, 51, 255));
        video1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Kumar\\Desktop\\videook.png")); // NOI18N
        video1.setText("Video ");
        video1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        video1.setOpaque(true);
        video1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                video1MouseClicked(evt);
            }
        });
        jPanel3.add(video1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 680, 350, 60));

        pictext1.setBackground(new java.awt.Color(51, 0, 51));
        pictext1.setFont(new java.awt.Font("Trajan Pro 3", 3, 24)); // NOI18N
        pictext1.setForeground(new java.awt.Color(51, 0, 255));
        pictext1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Kumar\\Desktop\\imageandtext.jpg")); // NOI18N
        pictext1.setText("Picture");
        pictext1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pictext1.setOpaque(true);
        pictext1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pictext1MouseClicked(evt);
            }
        });
        jPanel3.add(pictext1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 780, 350, 60));

        videotxt1.setBackground(new java.awt.Color(51, 0, 51));
        videotxt1.setFont(new java.awt.Font("Trajan Pro 3", 3, 24)); // NOI18N
        videotxt1.setForeground(new java.awt.Color(51, 51, 255));
        videotxt1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Kumar\\Desktop\\videoandtext.jpg")); // NOI18N
        videotxt1.setText("Video/Text");
        videotxt1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        videotxt1.setOpaque(true);
        videotxt1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                videotxt1MouseClicked(evt);
            }
        });
        videotxt1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                videotxt1KeyPressed(evt);
            }
        });
        jPanel3.add(videotxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-350, 380, 350, 60));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Kumar\\Documents\\NetBeansProjects\\DigitalSignage\\src\\com\\components\\playlist.jpg")); // NOI18N
        jLabel6.setPreferredSize(new java.awt.Dimension(1395, 672));
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1350, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 1350, 540));

        jTabbedPane1.addTab("Setup Playlist", jPanel3);
        jTabbedPane1.addTab("Setup Playlist", icon3, jPanel3);

        jButton2.setFont(new java.awt.Font("Trajan Pro", 3, 24)); // NOI18N
        jButton2.setText("clear playlist video\n");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Trajan Pro", 3, 24)); // NOI18N
        jButton4.setText("clear playlist video/text ");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(946, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jButton2)
                .addGap(73, 73, 73)
                .addComponent(jButton4)
                .addContainerGap(460, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Manage Content", jPanel4);
        jTabbedPane1.addTab("Manage Content", icon4, jPanel4);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked

      
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
       
    }//GEN-LAST:event_jPanel1MouseClicked

    private void videotxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_videotxtKeyPressed
      
    }//GEN-LAST:event_videotxtKeyPressed

    private void pictextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pictextMouseClicked
        picturescreen  l1=new picturescreen();
        if(!l1.isVisible())
          {   
              l1.setVisible(true);
          }     
    }//GEN-LAST:event_pictextMouseClicked

    private void videoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_videoMouseClicked

        videoscreen  l1=new videoscreen();
        if(!l1.isVisible())
          {   
              l1.setVisible(true);
          }     
    }//GEN-LAST:event_videoMouseClicked

    private void videotxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_videotxtMouseClicked
videotxt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/components/buttons/Videodefault.png")));
        videotext l1=new videotext();
        if(!l1.isVisible())
          {   
              l1.setVisible(true);
          }    
    }//GEN-LAST:event_videotxtMouseClicked

    private void jLabel4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel4KeyPressed
       
    }//GEN-LAST:event_jLabel4KeyPressed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        store l1=new store();
        if(!l1.isVisible())
          {   
              l1.setVisible(true);
          }    
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel5KeyPressed
    
    }//GEN-LAST:event_jLabel5KeyPressed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
      
        ac.jLabelXRight(-350, 450, 5, 7, video);
         ac.jLabelXRight(-350,  500, 5, 7, pictext);
         ac.jLabelXRight(-350, 550, 5, 7, videotxt);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         ac.jLabelYUp(680, 190, 5, 7, video1);
         ac.jLabelYUp(780,  290, 5, 7, pictext1);
        ac.jLabelXRight(-350, 400, 5, 7, videotxt1);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void video1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_video1MouseClicked
          layout2media l1=new layout2media();
        if(!l1.isVisible())
          {   
              l1.setVisible(true);
          }     
    }//GEN-LAST:event_video1MouseClicked

    private void pictext1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pictext1MouseClicked
         storepic l1=new storepic();
        if(!l1.isVisible())
          {   
              l1.setVisible(true);
          }    
    }//GEN-LAST:event_pictext1MouseClicked

    private void videotxt1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_videotxt1MouseClicked
       layouttest l1=new layouttest();
        if(!l1.isVisible())
          {   
              l1.setVisible(true);
          }    
    }//GEN-LAST:event_videotxt1MouseClicked

    private void videotxt1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_videotxt1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_videotxt1KeyPressed

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
    ImageIcon II = new ImageIcon(getClass().getResource("/com/components/buttons/Untitled-2.png"));
    jLabel5.setIcon(II);
    }//GEN-LAST:event_jLabel5MouseEntered

    private void jLabel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseExited
    ImageIcon II = new ImageIcon(getClass().getResource("/com/components/buttons/Untitled-1.png"));
    jLabel5.setIcon(II);
    }//GEN-LAST:event_jLabel5MouseExited

    private void jLabel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MousePressed
    ImageIcon II = new ImageIcon(getClass().getResource("/com/components/buttons/Untitled-3.png"));
    jLabel5.setIcon(II);
    }//GEN-LAST:event_jLabel5MousePressed

    private void videoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_videoMouseEntered
    ImageIcon II= new ImageIcon(getClass().getResource("/com/components/buttons/hover.png"));
    video.setIcon(II);
    }//GEN-LAST:event_videoMouseEntered

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
    
    }//GEN-LAST:event_jLabel1MouseEntered

    private void videoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_videoMousePressed
     ImageIcon II= new ImageIcon(getClass().getResource("/com/components/buttons/pressed.png"));
    video.setIcon(II);
    }//GEN-LAST:event_videoMousePressed

    private void videoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_videoMouseExited
     ImageIcon II= new ImageIcon(getClass().getResource("/com/components/buttons/default.png"));
    video.setIcon(II);
    }//GEN-LAST:event_videoMouseExited

    private void pictextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pictextMouseEntered
           ImageIcon II= new ImageIcon(getClass().getResource("/com/components/buttons/Picturehover.png"));
    pictext.setIcon(II);
    }//GEN-LAST:event_pictextMouseEntered

    private void pictextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pictextMouseExited
        ImageIcon II= new ImageIcon(getClass().getResource("/com/components/buttons/Picturedefault.png"));
    pictext.setIcon(II);
    }//GEN-LAST:event_pictextMouseExited

    private void pictextMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pictextMousePressed
        pictext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/components/buttons/picturepressed.png"))); 
    }//GEN-LAST:event_pictextMousePressed

    private void videotxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_videotxtMouseEntered
    ImageIcon II= new ImageIcon(getClass().getResource("/com/components/buttons/Videohover.png"));
    videotxt.setIcon(II);    
    }//GEN-LAST:event_videotxtMouseEntered

    private void videotxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_videotxtMouseExited
       ImageIcon II= new ImageIcon(getClass().getResource("/com/components/buttons/Videodefault.png"));
    videotxt.setIcon(II);
    }//GEN-LAST:event_videotxtMouseExited

    private void videotxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_videotxtMousePressed
     ImageIcon II= new ImageIcon(getClass().getResource("/com/components/buttons/videopressed.png"));
    videotxt.setIcon(II);
    }//GEN-LAST:event_videotxtMousePressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    try{
        
                String runSQL = "delete from layout2media1 "; 
                pst = connection.prepareStatement(runSQL);
                 pst.execute();
                 
            JOptionPane.showMessageDialog(null, "all media deleted from 1");
        }
       catch(SQLException | NumberFormatException e){
            JOptionPane.showMessageDialog(null, e);
       }  
       try{
        
                String runSQL = "delete from layout2media2 "; 
                pst = connection.prepareStatement(runSQL);
                 pst.execute();
                 
            JOptionPane.showMessageDialog(null, "all media deleted from 2");
        }
       catch(SQLException | NumberFormatException e){
            JOptionPane.showMessageDialog(null, e);
       }  
          try{
        
                String runSQL = "delete from layout2media3 "; 
                pst = connection.prepareStatement(runSQL);
                 pst.execute();
                 
            JOptionPane.showMessageDialog(null, "all media deleted from 3");
        }
       catch(SQLException | NumberFormatException e){
            JOptionPane.showMessageDialog(null, e);
       }  
             try{
        
                String runSQL = "delete from layout2media4 "; 
                pst = connection.prepareStatement(runSQL);
                 pst.execute();
                 
            JOptionPane.showMessageDialog(null, "all media deleted from 4");
        }
       catch(SQLException | NumberFormatException e){
            JOptionPane.showMessageDialog(null, e);
       }  
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
                  try{
        
                String runSQL = "delete from layout1media1 "; 
                pst = connection.prepareStatement(runSQL);
                 pst.execute();
                 
            JOptionPane.showMessageDialog(null, "all media deleted from 1");
        }
       catch(SQLException | NumberFormatException e){
            JOptionPane.showMessageDialog(null, e);
       }  
             try{
        
                String runSQL = "delete from layout1media2 "; 
                pst = connection.prepareStatement(runSQL);
                 pst.execute();
                 
            JOptionPane.showMessageDialog(null, "all media deleted from 2");
        }
       catch(SQLException | NumberFormatException e){
            JOptionPane.showMessageDialog(null, e);
       
    }                                        

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        textscrollWizard t = new textscrollWizard();
        t.setVisible(true);
        jPanel6.add(t);

    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel pictext;
    private javax.swing.JLabel pictext1;
    private javax.swing.JLabel video;
    private javax.swing.JLabel video1;
    private javax.swing.JLabel videotxt;
    private javax.swing.JLabel videotxt1;
    // End of variables declaration//GEN-END:variables
 protected static ImageIcon createImageIcon(String path) {
        java.net.URL imgURL = Home.class.getResource(path);
        if (imgURL != null) {
            return new ImageIcon(imgURL);
        } else {
            System.err.println("Couldn't find file: " + path);
            return null;
        }
    }
     

    public void glide() {
          ac.jLabelXRight(-350, 450, 5, 7, video);
         ac.jLabelXRight(-350,  500, 5, 7, pictext);
         ac.jLabelXRight(-350, 550, 5, 7, videotxt);
    }


}

