/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.components.wizard;

import com.components.textscroll.textscrollWizard;
import com.components.mysqlconnect;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import org.apache.commons.io.FilenameUtils;

/**
 *
 * @author lenovo
 */
public class layouttest extends javax.swing.JFrame {

    Connection connection = null;
PreparedStatement pst = null;
ResultSet rs = null;
    public layouttest() {
        initComponents();
        connection = mysqlconnect.ConnectDb();
        showtabel();
        fill();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        media1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        media2 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        pathfield = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 850, -1));

        jButton2.setText("Remove");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 420, 100, -1));

        media1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jScrollPane1.setViewportView(media1);
        if (media1.getColumnModel().getColumnCount() > 0) {
            media1.getColumnModel().getColumn(0).setPreferredWidth(2);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 120, 230, 190));

        media2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jScrollPane2.setViewportView(media2);
        if (media2.getColumnModel().getColumnCount() > 0) {
            media2.getColumnModel().getColumn(0).setPreferredWidth(2);
        }

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, 230, 190));

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jList1);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 300, 200));

        jButton3.setText("ADD to Media1");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, -1, -1));

        jButton4.setText("ADD to Media2");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, -1, -1));

        pathfield.setText("Path");
        pathfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pathfieldActionPerformed(evt);
            }
        });
        getContentPane().add(pathfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 230, -1));

        jButton1.setText("Scrolling text control");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
 public void showtabel() {
       try{
        
                String runSQL = "select * from layout1media1"; 
                pst = connection.prepareStatement(runSQL);
               rs=pst.executeQuery(runSQL);
               media1.setModel(DbUtils.resultSetToTableModel(rs));
            
        }
       catch(SQLException | NumberFormatException e){
          
       }
        
        try{
        
                String runSQL = "select * from layout1media2"; 
                pst = connection.prepareStatement(runSQL);
               rs=pst.executeQuery(runSQL);
               media2.setModel(DbUtils.resultSetToTableModel(rs));
            
        }
       catch(SQLException | NumberFormatException e){
          
       }
        
    }
    
    
    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         String mediaID ="SELECT COUNT(*) FROM layout1;";
        int rowCount = 0;
        try{
        pst = connection.prepareStatement(mediaID);
        rs = pst.executeQuery();
        if (rs.next()) {
        rowCount = rs.getInt(1);
                 }
        }   catch (SQLException | NumberFormatException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        ++rowCount;
      try{
        
                String runSQL = "insert into layout1(idmedia,path) values (?,?)"; 
                pst = connection.prepareStatement(runSQL);
                  pst.setString(1, Integer.toString(rowCount));
                pst.setString(2,jTextField1.getText());
                pst.execute();
            JOptionPane.showMessageDialog(null, "text saved");
        }
       catch(SQLException | NumberFormatException e){
            JOptionPane.showMessageDialog(null, "media saved");
       }
    }//GEN-LAST:event_jButton2ActionPerformed
private void fill(){
DefaultListModel m=new DefaultListModel();
    try {
        String sql="select * from media";
        pst=connection.prepareStatement(sql);
        rs=pst.executeQuery();
        while (rs.next()) {
            String path=rs.getString("name");
            m.addElement(path);
            }
        jList1.setModel(m);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);
    }finally{
        try {
            rs.close();
            pst.close();
        } catch (Exception e) {
        }
    }

}
    
    
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
            String mediaID ="SELECT COUNT(*) FROM layout1media1;";
        int rowCount = 0;
        try{
        pst = connection.prepareStatement(mediaID);
        rs = pst.executeQuery();
        if (rs.next()) {
        rowCount = rs.getInt(1);
                 }
        }   catch (SQLException | NumberFormatException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        ++rowCount;
      try{
        
                String runSQL = "insert into layout1media1 (no,path) values (?,?)"; 
                pst = connection.prepareStatement(runSQL);
                  pst.setString(1, Integer.toString(rowCount));
                pst.setString(2,pathfield.getText());
                 pst.execute();
            JOptionPane.showMessageDialog(null, "media saved");
        }
       catch(SQLException | NumberFormatException e){
            JOptionPane.showMessageDialog(null, e);
       }
        
        showtabel();
       
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        String tmp=(String)jList1.getSelectedValue();
        String sql="select * from media where name=?";
        try {
            pst=connection.prepareStatement(sql);
            pst.setString(1, tmp);
            rs=pst.executeQuery();
            if (rs.next()) {
                String add1=rs.getString("path");
                pathfield.setText(add1);
                
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jList1MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
         String mediaID ="SELECT COUNT(*) FROM layout1media2;";
        int rowCount = 1;
        try{
        pst = connection.prepareStatement(mediaID);
        rs = pst.executeQuery();
        if (rs.next()) {
        rowCount = rs.getInt(1);
                 }
        }   catch (SQLException | NumberFormatException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        ++rowCount;
      try{
        
                String runSQL = "insert into layout1media2 (no,path) values (?,?)"; 
                pst = connection.prepareStatement(runSQL);
                  pst.setString(1, Integer.toString(rowCount));
                pst.setString(2,pathfield.getText());
                 pst.execute();
            JOptionPane.showMessageDialog(null, "media saved");
        }
       catch(SQLException | NumberFormatException e){
            JOptionPane.showMessageDialog(null, e);
       }
        
        showtabel();
                                            

    }//GEN-LAST:event_jButton4ActionPerformed

    private void pathfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pathfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pathfieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    textscrollWizard t = new textscrollWizard();
    t.setVisible(true);
    
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(layouttest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(layouttest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(layouttest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(layouttest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new layouttest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable media1;
    private javax.swing.JTable media2;
    private javax.swing.JTextField pathfield;
    // End of variables declaration//GEN-END:variables
}
